In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df = pd.read_pickle("../../Data/New/Main_Data/Dataset_Removed_Countries.pkl")

In [22]:
df

Country  Year               Status  Life_Expectancy Adult_Mortality  \
0     Afghanistan  2014           Low income             63.0             234   
1     Afghanistan  2013           Low income             62.7             235   
2     Afghanistan  2012           Low income             62.2             242   
3     Afghanistan  2011           Low income             61.7             248   
4     Afghanistan  2010           Low income             61.2             255   
5     Afghanistan  2009           Low income             60.7             260   
6     Afghanistan  2008           Low income             60.2             265   
7     Afghanistan  2007           Low income             59.6             273   
8     Afghanistan  2006           Low income             59.2             276   
9     Afghanistan  2005           Low income             58.9             277   
10    Afghanistan  2004           Low income             58.4             282   
11    Afghanistan  2003           Low income             58.0             286   
12    Afghanistan  2002           Low income             57.4             292   
13    Afghanistan  2001           Low income             56.5             307   
14    Afghanistan  2000           Low income             55.9             316   
15        Albania  2014  Upper middle income             76.1              98   
16        Albania  2013  Upper middle income             75.7             100   
17        Albania  2012  Upper middle income             75.2             103   
18        Albania  2011  Upper middle income             75.1             103   
19        Albania  2010  Upper middle income             74.7             103   
20        Albania  2009  Upper middle income             74.4             103   
21        Albania  2008  Upper middle income             74.2             102   
22        Albania  2007  Upper middle income             74.1             101   
23        Albania  2006  Upper middle income             73.9             101   
24        Albania  2005  Upper middle income             73.5             106   
25        Albania  2004  Upper middle income             73.3             101   
26        Albania  2003  Upper middle income             72.9             107   
27        Albania  2002  Upper middle income             73.5             102   
28        Albania  2001  Upper middle income             74.0             100   
29        Albania  2000  Upper middle income             73.1             106   
...           ...   ...                  ...              ...             ...   
3210  Yemen, Rep.  2014           Low income             65.1             226   
3211  Yemen, Rep.  2013           Low income             65.1             225   
3212  Yemen, Rep.  2012           Low income             64.6             234   
3213  Yemen, Rep.  2011           Low income             64.6             234   
3214  Yemen, Rep.  2010           Low income             64.5             234   
3215  Yemen, Rep.  2009           Low income             64.3             236   
3216  Yemen, Rep.  2008           Low income             64.0             239   
3217  Yemen, Rep.  2007           Low income             63.7             241   
3218  Yemen, Rep.  2006           Low income             63.3             243   
3219  Yemen, Rep.  2005           Low income             62.9             246   
3220  Yemen, Rep.  2004           Low income             62.5             248   
3221  Yemen, Rep.  2003           Low income             62.0             249   
3222  Yemen, Rep.  2002           Low income             61.5             250   
3223  Yemen, Rep.  2001           Low income             61.1             251   
3224  Yemen, Rep.  2000           Low income             60.7             251   
3225       Zambia  2014  Lower middle income             61.2             299   
3226       Zambia  2013  Lower middle income             60.5             311   
3227       Zambia  2012  Lower middle inc

In [4]:
df[df['Country'] == "Albania"]['Measles']

15    NaN
16      0
17      9
18     28
19     10
20      0
21    NaN
22     22
23     68
24      6
25      7
26      8
27     16
28     18
29    662
Name: Measles, dtype: object

In [5]:
xxxx = df.columns[df.isnull().any()]
xxxx

Index(['Alcohol', 'Percentage_Expenditure', 'Measles', 'Polio',
       'Total_Expenditure', 'Diphtheria', 'GDP',
       'Income_Composition_Of_Resources', 'Schooling'],
      dtype='object')

In [6]:
for country in df['Country'].unique():
    for column in range(0, len(xxxx)):
        print(column)
        if(df[df['Country'] == country][xxxx[column]].isnull().any()):
            print(xxxx[column])
            print(country, column)
            # DEALING WITH MISSING VALUES
            imp = SimpleImputer(strategy='mean')
            replaced_array = imp.fit_transform(df[df['Country'] == country][[xxxx[column]]])
            print(replaced_array)
            # Replacing Values
            count = 0
            start_index = df[df['Country'] == country][xxxx[column]].index[0]
            end_index = df[df['Country'] == country][xxxx[column]].index[-1]
            for row in range(start_index, end_index+1):
                df.at[row, xxxx[column]] = replaced_array[count][0]
                count+=1

0
1
Percentage_Expenditure
Afghanistan 1
[[ 9.7]
 [ 8.8]
 [ 7.9]
 [ 8.6]
 [ 8.6]
 [ 9.8]
 [10.3]
 [ 9.9]
 [10.6]
 [ 9.9]
 [ 9.8]
 [ 8.9]
 [ 9.4]
 [ 9.4]
 [ 9.4]]
2
3
4
Total_Expenditure
Afghanistan 4
[[12.        ]
 [10.59      ]
 [11.67      ]
 [10.17      ]
 [14.4       ]
 [12.73      ]
 [ 6.93      ]
 [ 2.95      ]
 [ 6.3       ]
 [ 5.49      ]
 [ 6.98      ]
 [ 5.58      ]
 [ 8.99      ]
 [ 8.82923077]
 [ 8.82923077]]
5
6
GDP
Afghanistan 6
[[625.33953883]
 [647.96646047]
 [648.51106959]
 [599.29762976]
 [550.51497398]
 [444.18440408]
 [370.38229398]
 [366.23044324]
 [269.22969302]
 [247.66413996]
 [216.70812885]
 [195.77663034]
 [184.49471212]
 [412.79231679]
 [412.79231679]]
7
Income_Composition_Of_Resources
Afghanistan 7
[[0.441]
 [0.443]
 [0.442]
 [0.426]
 [0.421]
 [0.413]
 [0.388]
 [0.386]
 [0.371]
 [0.367]
 [0.357]
 [0.362]
 [0.357]
 [0.398]
 [0.398]]
8
0
1
2
Measles
Albania 2
[[ 65.69230769]
 [  0.        ]
 [  9.        ]
 [ 28.        ]
 [ 10.        ]
 [  0.        ]
 [ 65

5
6
7
8
0
1
2
Measles
Kenya 2
[[3.54000000e+02]
 [1.90000000e+02]
 [3.01478571e+03]
 [2.39500000e+03]
 [9.50000000e+01]
 [1.21800000e+03]
 [1.28200000e+03]
 [1.51600000e+03]
 [1.84700000e+03]
 [1.53000000e+02]
 [2.00000000e+01]
 [6.50000000e+01]
 [7.66000000e+02]
 [1.13040000e+04]
 [2.10020000e+04]]
3
4
5
6
7
8
0
1
2
Measles
Kiribati 2
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
3
4
5
6
7
8
0
1
2
Measles
Latvia 2
[[36.        ]
 [ 0.        ]
 [ 3.        ]
 [ 1.        ]
 [ 0.        ]
 [ 0.        ]
 [ 3.        ]
 [ 0.        ]
 [ 7.        ]
 [ 2.        ]
 [ 0.        ]
 [ 4.07692308]
 [ 4.07692308]
 [ 1.        ]
 [ 0.        ]]
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
Schooling
Lebanon 8
[[8.4 ]
 [8.3 ]
 [8.1 ]
 [8.  ]
 [7.9 ]
 [7.9 ]
 [7.8 ]
 [7.8 ]
 [7.6 ]
 [7.5 ]
 [7.93]
 [7.93]
 [7.93]
 [7.93]
 [7.93]]
0
1
2
Measles
Lesotho 2
[[0.00000000e+00]
 [5.16000000e+02]
 [1.79000000e+02]
 [1.72000000e+02]
 [2.48800000e+03]
 [0.00000000e+00]
 [0.000

[[76.        ]
 [82.        ]
 [83.        ]
 [66.        ]
 [72.        ]
 [78.        ]
 [79.        ]
 [70.        ]
 [62.        ]
 [55.        ]
 [57.        ]
 [55.        ]
 [38.        ]
 [67.15384615]
 [67.15384615]]
4
5
Diphtheria
Timor-Leste 5
[[77.        ]
 [82.        ]
 [83.        ]
 [67.        ]
 [72.        ]
 [72.        ]
 [79.        ]
 [70.        ]
 [63.        ]
 [55.        ]
 [57.        ]
 [55.        ]
 [54.        ]
 [68.15384615]
 [68.15384615]]
6
7
8
0
1
2
3
4
5
6
7
8
0
Alcohol
Tonga 0
[[1.31142857]
 [0.37      ]
 [0.54      ]
 [0.96      ]
 [1.24      ]
 [1.08      ]
 [1.1       ]
 [2.05      ]
 [1.79      ]
 [1.57      ]
 [1.79      ]
 [1.79      ]
 [1.5       ]
 [1.34      ]
 [1.24      ]]
1
2
Measles
Tonga 2
[[0.28571429]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [4.        ]
 [0.        ]]
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
0
1
2

In [7]:
#df[df['Country'] == country][[xxxx[6]]]
country = "Afghanistan"
column = 1
df[df['Country'] == country][xxxx[column]]
replaced_array[0][0]

815.0

In [8]:
df[df['Country'] == country][xxxx[column]].index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [9]:
df.isnull().any()

Country                            False
Year                               False
Status                             False
Life_Expectancy                    False
Adult_Mortality                    False
Infant_Deaths                      False
Alcohol                            False
Percentage_Expenditure             False
Measles                            False
BMI_5-19_years                     False
BMI_18+_years                      False
Under-Five_Deaths                  False
Polio                              False
Total_Expenditure                  False
Diphtheria                         False
GDP                                False
Population                         False
Thinness_10-19_years               False
Thinness_5-9_years                 False
Income_Composition_Of_Resources    False
Schooling                          False
dtype: bool

In [10]:
df.dtypes

Country                             object
Year                                 int64
Status                              object
Life_Expectancy                     object
Adult_Mortality                     object
Infant_Deaths                       object
Alcohol                             object
Percentage_Expenditure              object
Measles                             object
BMI_5-19_years                      object
BMI_18+_years                       object
Under-Five_Deaths                   object
Polio                               object
Total_Expenditure                   object
Diphtheria                          object
GDP                                 object
Population                         float64
Thinness_10-19_years                object
Thinness_5-9_years                  object
Income_Composition_Of_Resources     object
Schooling                           object
dtype: object

TypeError: read_pickle() got an unexpected keyword argument 'dtype'

In [39]:
df.Life_Expectancy = df.Life_Expectancy.astype(np.float64)
df.Adult_Mortality = df.Adult_Mortality.astype(np.int64)
df.Infant_Deaths = df.Infant_Deaths.astype(np.float64)
df.Alcohol = df.Alcohol.astype(np.float64)
df.Percentage_Expenditure = df.Percentage_Expenditure.astype(np.float64)
df.Measles = df.Measles.astype(np.float64)
df['BMI_5-19_years']  = df['BMI_5-19_years'] .astype(np.float64)
df['BMI_18+_years']  = df['BMI_18+_years'].astype(np.float64)
df.Polio= df.Polio.astype(np.int64)
df['Under-Five_Deaths']= df['Under-Five_Deaths'].astype(np.float64)
df.Total_Expenditure = df.Total_Expenditure .astype(np.float64)
df.Diphtheria = df.Diphtheria .astype(np.int64)
df.GDP = df.GDP.astype(np.float64)
df['Thinness_10-19_years']  = df['Thinness_10-19_years'].astype(np.float64)
df['Thinness_5-9_years']   = df['Thinness_5-9_years'].astype(np.float64)
df.Income_Composition_Of_Resources = df.Income_Composition_Of_Resources.astype(np.float64)
df.Schooling  = df.Schooling.astype(np.float64)

In [40]:
df.head()

Country  Year      Status  Life_Expectancy  Adult_Mortality  \
0  Afghanistan  2014  Low income             63.0              234   
1  Afghanistan  2013  Low income             62.7              235   
2  Afghanistan  2012  Low income             62.2              242   
3  Afghanistan  2011  Low income             61.7              248   
4  Afghanistan  2010  Low income             61.2              255   

   Infant_Deaths  Alcohol  Percentage_Expenditure  Measles  BMI_5-19_years  \
0           64.0     0.03                     9.7    492.0            17.2   
1           66.0     0.03                     8.8    430.0            17.1   
2           69.0     0.04                     7.9   2787.0            17.0   
3           71.0     0.04                     8.6   3013.0            16.9   
4           74.0     0.03                     8.6   1989.0            16.8   

   ...  Under-Five_Deaths  Polio  Total_Expenditure  Diphtheria         GDP  \
0  ...               86.0     58              12.00          62  625.339539   
1  ...               89.0     62              10.59          64  647.966460   
2  ...               93.0     67              11.67          67  648.511070   
3  ...               97.0     68              10.17          68  599.297630   
4  ...              101.0     66              14.40          66  550.514974   

   Population  Thinness_10-19_years  Thinness_5-9_years  \
0  32758020.0                  17.7                17.7   
1  31731688.0                  17.9                18.0   
2  30696958.0                  18.2                18.2   
3  29708599.0                  18.4                18.4   
4  28803167.0                  18.6                18.7   

   Income_Composition_Of_Resources  Schooling  
0                            0.441        3.5  
1                            0.443        3.5  
2                            0.442        3.4  
3                            0.426        3.3  
4                            0.421        3.2  

[5 rows x 21 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2070 entries, 0 to 3239
Data columns (total 21 columns):
Country                            2070 non-null object
Year                               2070 non-null int64
Status                             2070 non-null object
Life_Expectancy                    2070 non-null float64
Adult_Mortality                    2070 non-null int64
Infant_Deaths                      2070 non-null float64
Alcohol                            2070 non-null float64
Percentage_Expenditure             2070 non-null float64
Measles                            2070 non-null float64
BMI_5-19_years                     2070 non-null float64
BMI_18+_years                      2070 non-null float64
Under-Five_Deaths                  2070 non-null float64
Polio                              2070 non-null int64
Total_Expenditure                  2070 non-null float64
Diphtheria                         2070 non-null int64
GDP                                2070 non-null

In [44]:
pd.to_pickle(df, "../../Data/New/Main_Data/Final_Dataset.pkl")

In [47]:
df.to_csv("../../Data/New/Main_Data/Final_Dataset.csv")